#!/usr/bin/env python3
# Parses the official AUSNUT 2023 "Food nutrient profiles" spreadsheet
# (FSANZ, CC BY 4.0 — https://foodstandards.gov.au/science-data/
# food-nutrient-databases/ausnut) into ausnut-foods.json, ready for
# 02-commit-to-db.mjs to upsert into public.ausnut_foods.
#
# Pure data transform — no network calls, no API cost, nothing to review
# for quality (this is real government-measured data, not a generated
# estimate) beyond making sure the column mapping below is right.

import json
import os
import openpyxl

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "AUSNUT 2023 - Food nutrient profiles.xlsx")
OUT = os.path.join(HERE, "ausnut-foods.json")

KJ_PER_KCAL = 4.184

# Column mapping: ausnut_foods column -> source header text (must match
# exactly, checked against the header row below).
COLUMN_MAP = {
    "id": "Public food key",
    "name": "Food name",
    "derivation": "Derivation",
    "calories_kj": "Energy with dietary fibre (kJ)",  # converted to kcal below
    "protein_g": "Protein (g)",
    "carbs_g": "Available carbohydrate, without sugar alcohols (g)",
    "fat_g": "Total fat (g)",
    "fibre_g": "Dietary fibre (g)",
    "sodium_mg": "Sodium (Na) (mg)",
    "sugar_g": "Total sugars (g)",
    "vitamin_a_mcg": "Vitamin A retinol equivalents (ug)",
    "vitamin_c_mg": "Vitamin C (mg)",
    "polyunsaturated_fat_g": "Total polyunsaturated fat (g)",
    "monounsaturated_fat_g": "Total monounsaturated fat (g)",
    "magnesium_mg": "Magnesium (Mg) (mg)",
    "zinc_mg": "Zinc (Zn) (mg)",
    "vitamin_b12_mcg": "Cobalamin (B12) (ug)",
    "folate_mcg": "Dietary folate equivalents (ug)",
}

# Nutrients added after the first import. Kept apart because they're written
# differently: to more decimal places (B vitamins are hundredths of a
# milligram, which 2 dp would round to zero) and — for the "extended" ones —
# a blank cell stays NULL instead of becoming 0.
#   column -> (source header, divisor to get the column's unit)
# The first group are nutrients the app already tracks that ausnut_foods used
# to leave out (so AUSNUT foods logged them as 0); the second group are new.
ALREADY_TRACKED = {
    "saturated_fat_g": ("Total saturated fat (g)", 1),
    "trans_fat_g": ("Total trans fatty acids (mg)", 1000),  # mg -> g
    "cholesterol_mg": ("Cholesterol (mg)", 1),
    "potassium_mg": ("Potassium (K) (mg)", 1),
    "added_sugar_g": ("Added sugars (g)", 1),
    "vitamin_d_mcg": ("Vitamin D3 equivalents (ug)", 1),
    "calcium_mg": ("Calcium (Ca) (mg)", 1),
    "iron_mg": ("Iron (Fe) (mg)", 1),
}
EXTENDED = {
    "thiamin_mg": ("Thiamin (B1) (mg)", 1),
    "riboflavin_mg": ("Riboflavin (B2) (mg)", 1),
    "niacin_mg": ("Niacin derived equivalents (mg)", 1),
    "vitamin_b6_mg": ("Pyridoxine (B6) (mg)", 1),
    "vitamin_e_mg": ("Vitamin E (mg)", 1),
    "phosphorus_mg": ("Phosphorus (P) (mg)", 1),
    "selenium_mcg": ("Selenium (Se) (ug)", 1),
    "iodine_mcg": ("Iodine (I) (ug)", 1),
    "omega3_mg": ("Total long chain omega 3 fatty acids (mg)", 1),
    "omega6_g": ("Linoleic acid (g)", 1),
    "ala_g": ("Alpha linolenic acid (g)", 1),
    "caffeine_mg": ("Caffeine (mg)", 1),
    "alcohol_g": ("Alcohol (g)", 1),
}
MORE_COLUMNS = {**ALREADY_TRACKED, **EXTENDED}


def num(v):
    if v is None:
        return 0
    return round(float(v), 2)


def precise(v, divisor=1):
    """None stays None (unknown); otherwise 4 decimal places."""
    if v is None or v == "":
        return None
    return round(float(v) / divisor, 4)


def sql_num(v):
    if v is None:
        return "null::numeric"
    return str(int(v)) if float(v).is_integer() else repr(v)


BACKFILL_PARTS = 3


def backfill_path(part):
    return os.path.join(HERE, "..", "..", "supabase", f"ausnut_micronutrients_backfill_part{part}of{BACKFILL_PARTS}.sql")


def write_backfill_sql(foods):
    """Writes the backfill as BACKFILL_PARTS files — one file is ~500 KB, more
    than is comfortable to paste into the Supabase SQL editor. Each part is
    independent and idempotent, so they can be run in any order, or re-run."""
    cols = list(MORE_COLUMNS)
    size = -(-len(foods) // BACKFILL_PARTS)
    for part in range(1, BACKFILL_PARTS + 1):
        chunk = foods[(part - 1) * size: part * size]
        lines = [
            f"-- AUSNUT micronutrient backfill, part {part} of {BACKFILL_PARTS} ({len(chunk)} foods).",
            "-- Fills the columns added to public.ausnut_foods by the \"Extended micronutrients\"",
            "-- block in supabase/schema.sql (run that block first). Run all "
            f"{BACKFILL_PARTS} parts, in any order.",
            "-- Generated by scripts/import-ausnut/01-parse-xlsx.py from the official AUSNUT 2023",
            "-- spreadsheet — do not edit by hand; re-run the script instead.",
            "--",
            "-- Safe to re-run: it only UPDATEs those columns on rows that already exist",
            "-- (matched by id) — nothing is deleted or inserted, so food search keeps",
            "-- working throughout.",
            "begin;",
        ]
        step = 250
        for i in range(0, len(chunk), step):
            batch = chunk[i:i + step]
            tuples = ",\n  ".join(
                "(" + ", ".join([repr(f["id"])] + [sql_num(f[c]) for c in cols]) + ")" for f in batch
            )
            sets = ", ".join(f"{c} = v.{c}" for c in cols)
            lines.append(
                f"update public.ausnut_foods a set {sets}\nfrom (values\n  {tuples}\n) as v(id, {', '.join(cols)})\nwhere a.id = v.id;"
            )
        lines.append("commit;")
        lines.append("")
        with open(backfill_path(part), "w") as f:
            f.write("\n".join(lines))


def main():
    wb = openpyxl.load_workbook(SRC, read_only=True, data_only=True)
    ws = wb["Food nutrient profiles"]
    rows = list(ws.iter_rows(values_only=True))

    header = rows[2]
    header_index = {name: i for i, name in enumerate(header) if name is not None}

    missing = [src for src in list(COLUMN_MAP.values()) + [h for h, _ in MORE_COLUMNS.values()] if src not in header_index]
    if missing:
        raise SystemExit(f"Header columns not found, mapping is stale: {missing}")

    idx = {key: header_index[src] for key, src in COLUMN_MAP.items()}

    foods = []
    seen_ids = set()
    for row in rows[3:]:
        if row[idx["id"]] is None:
            continue
        food_id = str(row[idx["id"]])
        if food_id in seen_ids:
            raise SystemExit(f"Duplicate id found in source data: {food_id}")
        seen_ids.add(food_id)

        foods.append({
            "id": food_id,
            "name": row[idx["name"]],
            "derivation": row[idx["derivation"]],
            "calories": num((row[idx["calories_kj"]] or 0) / KJ_PER_KCAL),
            "protein_g": num(row[idx["protein_g"]]),
            "carbs_g": num(row[idx["carbs_g"]]),
            "fat_g": num(row[idx["fat_g"]]),
            "fibre_g": num(row[idx["fibre_g"]]),
            "sodium_mg": num(row[idx["sodium_mg"]]),
            "sugar_g": num(row[idx["sugar_g"]]),
            "vitamin_a_mcg": num(row[idx["vitamin_a_mcg"]]),
            "vitamin_c_mg": num(row[idx["vitamin_c_mg"]]),
            "polyunsaturated_fat_g": num(row[idx["polyunsaturated_fat_g"]]),
            "monounsaturated_fat_g": num(row[idx["monounsaturated_fat_g"]]),
            "magnesium_mg": num(row[idx["magnesium_mg"]]),
            "zinc_mg": num(row[idx["zinc_mg"]]),
            "vitamin_b12_mcg": num(row[idx["vitamin_b12_mcg"]]),
            "folate_mcg": num(row[idx["folate_mcg"]]),
            **{
                col: precise(row[header_index[src]], divisor)
                for col, (src, divisor) in MORE_COLUMNS.items()
            },
        })

    with open(OUT, "w") as f:
        json.dump(foods, f, indent=2)

    write_backfill_sql(foods)
    print(f"Parsed {len(foods)} foods -> {OUT}")
    print(f"Backfill SQL -> supabase/ausnut_micronutrients_backfill_part1..{BACKFILL_PARTS}of{BACKFILL_PARTS}.sql")


if __name__ == "__main__":
    main()
